services:
  db:
    image: postgres:16.4
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: api-rest-spring
    ports:
      - 5433:5432
    networks:
      - api-network

  api-rest-spring:
    image: renatofari4s/api-rest-spring
    build: .
    working_dir: /api-rest-spring
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://db:5432/api-rest-spring
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 80:8080

    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - api-network

networks:
  api-network:
    driver: bridge