cors:
  originPatterns: http://localhost:8080,http://localhost:3000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?timezone=America/Sao_Paulo
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true