cors:
  originPatterns: http://localhost:8080,http://localhost:3000
file:
  upload-dir: /Code/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?timezone=America/Sao_Paulo
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    hibernate:
      ddl-auto: none
    show-sql: false
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 2KB
        max-file-size: 200MB
        max-request-size: 215MB
springdoc:
  pathsToMatch:
    - /api/**/v1/**
    - /auth/**
  swagger-ui:
    use-root-path: true